# 翻译服务类型: qcloud 或 auzer
translate_type: qcloud

# 腾讯云配置
qcloud:
  secret_id: "your-secret-id"
  secret_key: "your-secret-key"
  region: "ap-guangzhou"
  project_id: 0

# Azure配置
auzer:
  resource_key: "your-azure-resource-key"
  endpoint: "https://api.cognitive.microsofttranslator.com/translate"
  region: "eastasia" 