name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     tags:
#       - "v*.*.*"



jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
    
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/
          zip -r translate-linux.zip build/
          echo "linux_zip_path=translate-linux.zip" >> $env:GITHUB_OUTPUT


  macOS-latest:
    runs-on: macos-latest
    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/
          zip -r translate-drawin.zip build/
          echo "macOS_zip_path=translate-drawin.zip" >> $env:GITHUB_OUTPUT


  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [Win32, x64]
        sdl2: [ON]
        include:
          - arch: Win32
            s2arc: x86
          - arch: x64
            s2arc: x64
    
    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/
          Compress-Archive -Path ./build -DestinationPath translate-${{ matrix.arch }}.zip
          echo "win_${{ matrix.arch }}_zip_path=translate-${{ matrix.arch }}.zip" >> $env:GITHUB_OUTPUT
          


  
  release:
    needs: [ubuntu-latest, macOS-latest, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          body: |
            Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Linux Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          asset_path: ${{ needs.ubuntu-latest.outputs.outputs.linux_zip_path }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: translate-linux.zip
          asset_content_type: application/zip

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          asset_path: ${{ needs.macOS-latest.outputs.macOS_zip_path }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: translate-drawin.zip
          asset_content_type: application/zip
