name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     tags:
#       - "v*.*.*"



jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: setenv
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
    
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: translate-linux
          path: build/

  macOS-latest:
    runs-on: macOS-latest

    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: translate-drawin
          path: build/