name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# on:
#   push:
#     tags:
#       - "v*.*.*"



jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
    
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: translate-linux
          path: build/

  macOS-latest:
    runs-on: macos-latest

    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: translate-drawin
          path: build/

  windows:
    runs-on: windows-latest

    strategy:
      matrix:
        build: [Release]
        arch: [Win32, x64]
        sdl2: [ON]
        include:
          - arch: Win32
            s2arc: x86
          - arch: x64
            s2arc: x64
    
    steps:
      - name: setenv
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
          
      - name: Clone
        uses: actions/checkout@v1

      - name: Build
        run: |
          make cmd
          ls build/

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: translate-${{ matrix.arch }}
          path: build/